version: '3.9'

services:
  backend:
    image: mindecho_backend:prod
    build: .
    container_name: mindecho_backend
    env_file: .env
    environment:
      - NODE_ENV=production
      - PG_PORT=5432
    expose:
      - "8443"           
    # depends_on:
    #   - postgres
    restart: always

  # postgres:
  #   image: postgres:16-alpine
  #   container_name: mindecho_postgres
  #   env_file: .env
  #   environment:
  #     - POSTGRES_DB=${PG_DATABASE}
  #     - POSTGRES_USER=${PG_USER}
  #     - POSTGRES_PASSWORD=${PG_PASSWORD}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data_prod:/var/lib/postgresql/data
  #   restart: always

  nginx:
    image: nginx:latest
    container_name: mindecho_nginx
    ports:
      - "80:80"          # 對外開放 HTTP
      - "443:443"        # 對外開放 HTTPS
    depends_on:
      - backend
      # - postgres
    volumes:
      # 掛載 nginx 設定
      - ./nginx:/etc/nginx:ro
    restart: always

volumes:
  postgres_data_prod:
