version: '3.9'

services:
  db-init:
    image: mindecho_backend:dev
    build:
      context: .
      target: dev
    container_name: mindecho_db_init
    env_file: .env
    environment:
      - NODE_ENV=development
      - PG_HOST=postgres
      - PG_PORT=5432
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}?schema=public
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma db push && npx prisma db execute --schema prisma/schema.prisma --file prisma/seed_scales.sql"
    restart: "no"

  backend:
    build:
      context: .
      target: dev
    image: mindecho_backend:dev
    container_name: mindecho_backend
    env_file: .env
    environment:
      - NODE_ENV=development
      - PG_HOST=postgres
      - PG_PORT=5432
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}?schema=public
    command: >
      sh -c "node src/server.js"
    expose:
      - "8442"
    depends_on:
      - postgres
      - db-init
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: mindecho_postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432" # host 5433 -> container 5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    container_name: mindecho_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 掛載自訂 nginx 設定
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      # - postgres
    restart: always

volumes:
  postgres_data_dev:
